/*
 * MainFrame.java
 *
 * Created on __DATE__, __TIME__
 */

package com.gaver.view;

import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.io.IOException;

import javax.swing.JFileChooser;

import bitoflife.chatterbean.AliceBot;
import bitoflife.chatterbean.util.Searcher;

import com.gaver.control.AIMLFileAdapter;
import com.gaver.control.AliceBotMother;
import com.gaver.domain.MyAIML;
import com.gaver.util.AIMLFileReader;
import com.gaver.util.NlpirTest;

/**
 * 
 * @author __USER__
 */
public class MainFrame extends javax.swing.JFrame {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8450974253017715286L;

	/** Creates new form MainFrame */
	public MainFrame() {
		initComponents();
		// 初始化文件搜索
		initBingings();
	}

	public int gIndex = 0;

	private MyAIML aiml;
	public static String amilDir = "Bots/Alice";
	public String filePath = "";
	public AliceBot bot = null;
	boolean[] mark;
	boolean isModifyMode = false;

	// TODO
	private void initBingings() {
		Searcher searcher = new Searcher();
		new AIMLFileAdapter(list1, searcher.dir(amilDir, ".*\\.aiml"));
		list1.addItemListener(new ItemListener() {

			@Override
			public void itemStateChanged(ItemEvent e) {
				Integer index = (Integer) e.getItem();
				filePath = list1.getItem(index);
				aiml = MyAIML.parseAIML(AIMLFileReader.readContent(filePath));
				gIndex = 0;
				mark = new boolean[aiml.catorages.size()];
				lb_size.setText(aiml.catorages.size() + "");
				txarea_patten
						.setText(aiml.catorages.get(gIndex).pattern.mContent);
				txarea_catorage
						.setText(aiml.catorages.get(gIndex).template.mContent);
				lb_pagenum.setText((gIndex + 1) + "");
			}
		});
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	// GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		jPanel1 = new javax.swing.JPanel();
		list1 = new java.awt.List();
		btn_open_aiml = new java.awt.Button();
		btn_change_aiml = new java.awt.Button();
		tit_1 = new java.awt.Label();
		jPanel2 = new javax.swing.JPanel();
		label1 = new java.awt.Label();
		label2 = new java.awt.Label();
		jScrollPane1 = new javax.swing.JScrollPane();
		txarea_catorage = new javax.swing.JTextArea();
		jScrollPane2 = new javax.swing.JScrollPane();
		txarea_patten = new javax.swing.JTextArea();
		btn_last_page = new javax.swing.JButton();
		btn_next_page = new javax.swing.JButton();
		lb_size = new javax.swing.JLabel();
		jLabel1 = new javax.swing.JLabel();
		jLabel2 = new javax.swing.JLabel();
		lb_pagenum = new javax.swing.JLabel();
		jLabel4 = new javax.swing.JLabel();
		jButton1 = new javax.swing.JButton();
		jPanel3 = new javax.swing.JPanel();
		button2 = new java.awt.Button();
		panel1 = new java.awt.Panel();
		tf_input = new java.awt.TextField();
		btn_send = new java.awt.Button();
		jScrollPane3 = new javax.swing.JScrollPane();
		txarea_errmesg = new javax.swing.JTextArea();
		jScrollPane4 = new javax.swing.JScrollPane();
		txarea_history = new javax.swing.JTextArea();
		btn_reload = new javax.swing.JButton();
		jMenuBar1 = new javax.swing.JMenuBar();
		jMenu1 = new javax.swing.JMenu();
		jMenu2 = new javax.swing.JMenu();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

		list1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				list1ActionPerformed(evt);
			}
		});

		btn_open_aiml.setActionCommand("btn_open_aiml");
		btn_open_aiml.setLabel("\u6253\u5f00\u76ee\u5f55");
		btn_open_aiml.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_open_aimlMouseClicked(evt);
			}
		});

		btn_change_aiml.setActionCommand("btn_save_aiml");
		btn_change_aiml.setLabel("\u4fee\u6539\u6587\u4ef6");
		btn_change_aiml.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_change_aimlMouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(
				jPanel1);
		jPanel1.setLayout(jPanel1Layout);
		jPanel1Layout
				.setHorizontalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addGap(18, 18, 18)
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addComponent(
																list1,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																197,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addGroup(
																jPanel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				btn_open_aiml,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				89,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				20,
																				20,
																				20)
																		.addComponent(
																				btn_change_aiml,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE)))
										.addContainerGap(
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)));
		jPanel1Layout
				.setVerticalGroup(jPanel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel1Layout
										.createSequentialGroup()
										.addContainerGap()
										.addGroup(
												jPanel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																btn_change_aiml,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE)
														.addComponent(
																btn_open_aiml,
																javax.swing.GroupLayout.PREFERRED_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.PREFERRED_SIZE))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												Short.MAX_VALUE)
										.addComponent(
												list1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												526,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap()));

		btn_open_aiml.getAccessibleContext().setAccessibleName("btn_open_btn");

		tit_1.setText("AIMLTest");

		label1.setText("\u5339\u914d");

		label2.setText("\u6a21\u677f");

		txarea_catorage.setColumns(20);
		txarea_catorage.setFont(new java.awt.Font("微软雅黑", 0, 18));
		txarea_catorage.setLineWrap(true);
		txarea_catorage.setRows(5);
		txarea_catorage.setWrapStyleWord(true);
		jScrollPane1.setViewportView(txarea_catorage);

		txarea_patten.setColumns(20);
		txarea_patten.setFont(new java.awt.Font("微软雅黑", 0, 18));
		txarea_patten.setRows(5);
		jScrollPane2.setViewportView(txarea_patten);

		btn_last_page.setText("\u4e0a\u4e00\u9875");
		btn_last_page.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_last_pageMouseClicked(evt);
			}
		});

		btn_next_page.setText("\u4e0b\u4e00\u9875");
		btn_next_page.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_next_pageMouseClicked(evt);
			}
		});

		lb_size.setText("0");

		jLabel1.setText("\u4e00\u5171\uff1a");

		jLabel2.setText("\u7b2c");

		lb_pagenum.setText("0");

		jLabel4.setText("\u9875");

		jButton1.setText("\u4fdd\u5b58");
		jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				jButton1MouseClicked(evt);
			}
		});

		javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(
				jPanel2);
		jPanel2.setLayout(jPanel2Layout);
		jPanel2Layout
				.setHorizontalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										19, 19, 19).addComponent(label1,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(636, Short.MAX_VALUE))
						.addComponent(jScrollPane2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 683,
								Short.MAX_VALUE)
						.addGroup(
								jPanel2Layout.createSequentialGroup().addGap(
										18, 18, 18).addComponent(label2,
										javax.swing.GroupLayout.PREFERRED_SIZE,
										javax.swing.GroupLayout.DEFAULT_SIZE,
										javax.swing.GroupLayout.PREFERRED_SIZE)
										.addContainerGap(637, Short.MAX_VALUE))
						.addComponent(jScrollPane1,
								javax.swing.GroupLayout.DEFAULT_SIZE, 683,
								Short.MAX_VALUE)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addContainerGap()
										.addComponent(btn_last_page)
										.addGap(54, 54, 54)
										.addComponent(jLabel1)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												lb_size,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												66,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(82, 82, 82)
										.addComponent(jLabel2)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(lb_pagenum)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
										.addComponent(jLabel4)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												80, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(37, 37,
												37).addComponent(btn_next_page)
										.addContainerGap()));
		jPanel2Layout
				.setVerticalGroup(jPanel2Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								jPanel2Layout
										.createSequentialGroup()
										.addComponent(
												label1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(1, 1, 1)
										.addComponent(
												jScrollPane2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												181,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addGap(2, 2, 2)
										.addComponent(
												label2,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												javax.swing.GroupLayout.DEFAULT_SIZE,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addComponent(
												jScrollPane1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												238,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												jPanel2Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.BASELINE)
														.addComponent(
																btn_last_page)
														.addComponent(
																btn_next_page)
														.addComponent(jLabel1)
														.addComponent(lb_size)
														.addComponent(jLabel2)
														.addComponent(
																lb_pagenum)
														.addComponent(jLabel4)
														.addComponent(jButton1))
										.addContainerGap()));

		button2.setLabel("button2");

		javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(
				jPanel3);
		jPanel3.setLayout(jPanel3Layout);
		jPanel3Layout.setHorizontalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(button2,
								javax.swing.GroupLayout.DEFAULT_SIZE, 91,
								Short.MAX_VALUE).addContainerGap()));
		jPanel3Layout.setVerticalGroup(jPanel3Layout.createParallelGroup(
				javax.swing.GroupLayout.Alignment.LEADING).addGroup(
				jPanel3Layout.createSequentialGroup().addContainerGap()
						.addComponent(button2,
								javax.swing.GroupLayout.PREFERRED_SIZE, 34,
								javax.swing.GroupLayout.PREFERRED_SIZE)
						.addContainerGap(503, Short.MAX_VALUE)));

		btn_send.setLabel("\u53d1\u9001");
		btn_send.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_sendMouseClicked(evt);
			}
		});

		txarea_errmesg.setColumns(20);
		txarea_errmesg.setLineWrap(true);
		txarea_errmesg.setRows(5);
		txarea_errmesg.setWrapStyleWord(true);
		jScrollPane3.setViewportView(txarea_errmesg);

		txarea_history.setColumns(20);
		txarea_history.setLineWrap(true);
		txarea_history.setRows(5);
		txarea_history.setWrapStyleWord(true);
		jScrollPane4.setViewportView(txarea_history);

		javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(
				panel1);
		panel1.setLayout(panel1Layout);
		panel1Layout
				.setHorizontalGroup(panel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panel1Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane3,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												436,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																panel1Layout
																		.createSequentialGroup()
																		.addComponent(
																				tf_input,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				394,
																				Short.MAX_VALUE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				btn_send,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				77,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addComponent(
																jScrollPane4,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																481,
																Short.MAX_VALUE))
										.addContainerGap()));
		panel1Layout
				.setVerticalGroup(panel1Layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								panel1Layout
										.createSequentialGroup()
										.addComponent(
												jScrollPane4,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												159,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												panel1Layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addComponent(
																tf_input,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																26,
																Short.MAX_VALUE)
														.addComponent(
																btn_send,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE))
										.addContainerGap()).addComponent(
								jScrollPane3,
								javax.swing.GroupLayout.DEFAULT_SIZE, 205,
								Short.MAX_VALUE));

		btn_reload.setText("\u91cd\u65b0\u52a0\u8f7d");
		btn_reload.addMouseListener(new java.awt.event.MouseAdapter() {
			public void mouseClicked(java.awt.event.MouseEvent evt) {
				btn_reloadMouseClicked(evt);
			}
		});

		jMenu1.setText("File");
		jMenuBar1.add(jMenu1);

		jMenu2.setText("Edit");
		jMenuBar1.add(jMenu2);

		setJMenuBar(jMenuBar1);

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				tit_1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				65,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel2,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addGap(
																				18,
																				18,
																				18)
																		.addComponent(
																				jPanel3,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				panel1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				btn_reload)))
										.addContainerGap()));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING,
																false)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				tit_1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				32,
																				javax.swing.GroupLayout.PREFERRED_SIZE)
																		.addPreferredGap(
																				javax.swing.LayoutStyle.ComponentPlacement.RELATED)
																		.addComponent(
																				jPanel1,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				javax.swing.GroupLayout.DEFAULT_SIZE,
																				Short.MAX_VALUE))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				87,
																				87,
																				87)
																		.addGroup(
																				layout
																						.createParallelGroup(
																								javax.swing.GroupLayout.Alignment.LEADING)
																						.addComponent(
																								jPanel2,
																								javax.swing.GroupLayout.PREFERRED_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.PREFERRED_SIZE)
																						.addComponent(
																								jPanel3,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								javax.swing.GroupLayout.DEFAULT_SIZE,
																								Short.MAX_VALUE))))
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED)
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.TRAILING)
														.addComponent(
																panel1,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																javax.swing.GroupLayout.DEFAULT_SIZE,
																Short.MAX_VALUE)
														.addComponent(
																btn_reload))
										.addContainerGap()));

		pack();
	}// </editor-fold>

	// GEN-END:initComponents

	private void btn_change_aimlMouseClicked(java.awt.event.MouseEvent evt) {
		// TODO add your handling code here:
		Searcher searcher = new Searcher();
		new AIMLFileAdapter(list1, searcher.dir("zh/" + amilDir, ".*\\.aiml"));
		isModifyMode = true;
	}

	// TODO
	private void btn_sendMouseClicked(java.awt.event.MouseEvent evt) {
		if (bot == null) {
			return;
		}
		try {
			String inputString = tf_input.getText();
			String sSpliteword = inputString;
			tf_input.setText("");
			try {
				sSpliteword = NlpirTest.spliteWord(inputString).replaceAll(
						"/\\S{1,}\\s", " ");
			} catch (Exception e) {
				e.printStackTrace();
			}
			txarea_errmesg.append(sSpliteword + "\n");
			txarea_history.append("你的输入>>>>" + inputString + "\n");
			String response = bot.respond(sSpliteword);
			txarea_history.append("机器人的回应>>>>" + response + "\n");
		} catch (NullPointerException e) {
			txarea_history.append("机器人的回应>>>>抱歉。没有找到匹配！" + "\n");
		}
	}

	// TODO add your handling code here:
	private void btn_reloadMouseClicked(java.awt.event.MouseEvent evt) {
		System.gc();
		try {
			AliceBotMother mother = new AliceBotMother();
			mother.setUp();
			bot = mother.newInstance();
			if (bot != null) {
				javax.swing.JOptionPane.showMessageDialog(null, "载入成功");
			}
		} catch (Exception e) {
			txarea_errmesg.setText(e.getMessage());
		}
	}

	// TODO
	private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {
		if ("".equals(filePath) || filePath == null) {
			return;
		}
		if (isModifyMode) {
			aiml.catorages.get(gIndex).pattern.mContent = txarea_patten
					.getText();
			aiml.catorages.get(gIndex).template.mContent = txarea_catorage
					.getText();
			File file = new File("zh/" + amilDir, (new File(filePath))
					.getName());
			File bakFile = new File(file + ".bak");
			file.renameTo(bakFile);
			System.out.println(file);
			if (aiml.writeFile("zh/" + amilDir, (new File(filePath)).getName())) {
				javax.swing.JOptionPane.showMessageDialog(null, "保存成功！");
				bakFile.delete();
			} else {
				bakFile.renameTo(file);
			}
		} else {
			if (mark[gIndex]) {
				javax.swing.JOptionPane.showMessageDialog(null, "已经保存过了！");
				return;
			}
			aiml.catorages.get(gIndex).pattern.mContent = txarea_patten
					.getText();
			aiml.catorages.get(gIndex).template.mContent = txarea_catorage
					.getText();
			if (aiml.catorages.get(gIndex).writeFile("zh/" + amilDir,
					(new File(filePath)).getName())) {
				mark[gIndex] = true;
				javax.swing.JOptionPane.showMessageDialog(null, "保存成功！");
			}
		}
	}

	private void btn_next_pageMouseClicked(java.awt.event.MouseEvent evt) {
		if (gIndex < aiml.catorages.size() - 1) {
			++gIndex;
			txarea_catorage
					.setText(aiml.catorages.get(gIndex).template.mContent);
			txarea_patten.setText(aiml.catorages.get(gIndex).pattern.mContent);
			lb_pagenum.setText((gIndex + 1) + "");
		} else if (gIndex == aiml.catorages.size() - 1) {
			txarea_catorage
					.setText(aiml.catorages.get(gIndex).template.mContent);
			txarea_patten.setText(aiml.catorages.get(gIndex).pattern.mContent);
			lb_pagenum.setText((gIndex + 1) + "");
		}
	}

	private void btn_last_pageMouseClicked(java.awt.event.MouseEvent evt) {
		if (gIndex > 0) {
			--gIndex;
			txarea_catorage
					.setText(aiml.catorages.get(gIndex).template.mContent);
			txarea_patten.setText(aiml.catorages.get(gIndex).pattern.mContent);
			lb_pagenum.setText((gIndex + 1) + "");
		} else if (gIndex == 0) {
			txarea_catorage
					.setText(aiml.catorages.get(gIndex).template.mContent);
			txarea_patten.setText(aiml.catorages.get(gIndex).pattern.mContent);
			lb_pagenum.setText((gIndex + 1) + "");
		}
	}

	// TODO
	private void btn_open_aimlMouseClicked(java.awt.event.MouseEvent evt) {
		JFileChooser jFileChooser = new JFileChooser();
		jFileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
		jFileChooser.showOpenDialog(this);
		File seleFile = jFileChooser.getSelectedFile();
		if (seleFile == null) {
			return;
		}
		Searcher searcher = new Searcher();
		try {
			new AIMLFileAdapter(list1, searcher.dir(
					seleFile.getCanonicalPath(), ".*\\.aiml"));
			isModifyMode = false;
		} catch (IOException e) {
			e.printStackTrace();
			return;
		}
		isModifyMode = false;
	}

	private void list1ActionPerformed(java.awt.event.ActionEvent evt) {

	}

	/**
	 * @param args
	 *            the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MainFrame().setVisible(true);
			}
		});
	}

	// GEN-BEGIN:variables
	// Variables declaration - do not modify
	private java.awt.Button btn_change_aiml;
	private javax.swing.JButton btn_last_page;
	private javax.swing.JButton btn_next_page;
	private java.awt.Button btn_open_aiml;
	private javax.swing.JButton btn_reload;
	private java.awt.Button btn_send;
	private java.awt.Button button2;
	private javax.swing.JButton jButton1;
	private javax.swing.JLabel jLabel1;
	private javax.swing.JLabel jLabel2;
	private javax.swing.JLabel jLabel4;
	private javax.swing.JMenu jMenu1;
	private javax.swing.JMenu jMenu2;
	private javax.swing.JMenuBar jMenuBar1;
	private javax.swing.JPanel jPanel1;
	private javax.swing.JPanel jPanel2;
	private javax.swing.JPanel jPanel3;
	private javax.swing.JScrollPane jScrollPane1;
	private javax.swing.JScrollPane jScrollPane2;
	private javax.swing.JScrollPane jScrollPane3;
	private javax.swing.JScrollPane jScrollPane4;
	private java.awt.Label label1;
	private java.awt.Label label2;
	private javax.swing.JLabel lb_pagenum;
	private javax.swing.JLabel lb_size;
	private java.awt.List list1;
	private java.awt.Panel panel1;
	private java.awt.TextField tf_input;
	private java.awt.Label tit_1;
	private javax.swing.JTextArea txarea_catorage;
	private javax.swing.JTextArea txarea_errmesg;
	private javax.swing.JTextArea txarea_history;
	private javax.swing.JTextArea txarea_patten;
	// End of variables declaration//GEN-END:variables

}